### PR TITLE
Fixing some easy issues

### PR DESCRIPTION
**Pull request by aaaschmitt**
Issues fixed entirely (and should be closed):
264, 265, 350, 383 
263 (can't get the stupid bullets to go away and didn't want to edit the CSS out of fear...doesn't really matter though)

Sort of fixed: 383

### CODE REVIEW

**Comment by cycomachead** [comment]
I will pull this when I wake up and look at the changes but it seems good! :)

**Comment by cycomachead** [comment]
@aaaschmitt Do you have the file you used to make the images?

**Comment by aaaschmitt** [comment]
I took pics of the file that is linked in the lab page so that the pics in
the lab are same as the starter file.

Andy

**Comment by cycomachead** [comment]
Ok, cool!

## 

Michael Ball
From my iPhone
michaelballphoto.com

**Pull request merged**
