### PR TITLE
created fa16 labs page

### PR DESCRIPTION
**Pull request by strollinghome**
Created the page for fa16, not sure if there's anything else I should do.

### CODE REVIEW

**Comment by cycomachead** [comment]
Change index.html to point to it,

And update _config in the Fa16 site.

**Comment by strollinghome** [comment]
Do you want me to add another link to the list of website? Should I leave the other ones as is or should we make the titles consistent?

**Comment by cycomachead** [comment]
I would copy the same format - put Fa16 link at the top, but keep the links to the other semesters on the bottom.

**Comment by strollinghome** [comment]
config looks fine, should I edit config-inst?

**Comment by cycomachead** [comment]
Probably.

Though no one does anything with that file so it doesn't really matter. 

It exists because there is a mythical world with unicorns and where our site gets backed up on each push. 

## 

Michael Ball
From my iPhone
michaelball.co

**Comment by strollinghome** [comment]
lol, everything should be set now.

**Comment by cycomachead** [comment]
Thanks.

**Pull request merged**
