### PR TITLE
Pull in the data lab...

### PR DESCRIPTION
**Pull request by fractor**
Hi all,

This is the data lab. Comments are still welcome.

Gerald

### CODE REVIEW

**Comment by cycomachead** [comment]
Looks good! :)

http://fractor.github.io/bjc-r/cur/programming/data/preprocess.html?topic=berkeley_bjc/areas/data.topic&step=2&course=
On the section about creating a bunch or coordinates in a text file, can we give some students guidance on this?
I don't think students are comfortable enough to create data and then use the split block to generate a list of 2-item lists. I feel like most people will start just typing in coordinates manually / randomly in a text file. And then won't have useful data to work with.

We should also give them a starter file with the sprite and background.

Additionally, we should have a Snap specific page on importing data with Snap and using split to get lists. The section on using the spam file shows it somewhat, but a little more explanation might be helpful.

Few small comments, but are things that I can fix:
- We already have the coordinates image in the labs directory: img/drawing/stage-coordinates.png
- The base 64 images, like [here](http://fractor.github.io/bjc-r/cur/programming/data/visualizing.html?topic=berkeley_bjc/areas/data.topic&step=3&course=) Should be saved a PNG to save browser rendering time. We should also probably have the image w/o a grey background.
- All images should be in img/somewhere
- The HTML pages should have an HTML 5 doctype. `<!DOCTYPE html>`
- Snap, should be written as `<span class="snap">snap</span>` whenever used in HTML.

Finally, @xtitter Should be add the link to this lab in Berkeley_BJC? Or just link to it on the CS10 page?

**Comment by fractor** [comment]
Michael et al.,

Thanks so much for taking a close look! See my responses inline.

http://fractor.github.io/bjc-r/cur/programming/data/preprocess.html?topic=berkeley_bjc/areas/data.topic&step=2&course=>
On the section about creating a bunch or coordinates in a text file, can we
give some students guidance on this?

> I don't think students are comfortable enough to create data and then use
> the split block to generate a list of 2-item lists. I feel like most people
> will > start just typing in coordinates manually / randomly in a text file.
> And then won't have useful data to work with.

The coordinates ARE GIVEN in the introduction, no need to create any. And I
WANT THEM to use a text editor and copy and paste them in and then do
pre-processing manually. This is intentional as a reaction to the strong
emphasize on pre-processing in the AP curriculum. Let me know if that's not
clear enough.

> We should also give them a starter file with the sprite and background.
> 
> OK. Can you create that as a backup? The reason I didn't do it is because I
> was hoping we don't need as we would be able to use Nate's tools. As of
> know I am not sure we can get them stable enough by the start of this.
> 
> Additionally, we should have a Snap specific page on importing data with
> Snap and using split to get lists. The section on using the spam file shows
> it somewhat, but a little more explanation might be helpful.
> 
> So for the GPS coordinates I don't want them to do that because I want them
> to copy and paste the coordinates into the list manually from the editor.
> For the spam/ham I just want them to reuse the code I gave them. Also:
> Don't they have experience with split already? Please advise.
> 
> Few small comments, but are things that I can fix:
> - We already have the coordinates image in the labs directory:
>   img/drawing/stage-coordinates.png
> - The base 64 images, like herehttp://fractor.github.io/bjc-r/cur/programming/data/visualizing.html?topic=berkeley_bjc/areas/data.topic&step=3&course=Should be saved a PNG to save browser rendering time. We should also
>   probably have the image w/o a grey background.
> 
> Can you provide me the source that says that this is faster? AFAIK inline
> images are much faster because you don't need a new network connection.
> Rendering time is not the bottleneck in browsers, network I/O is.

We can have SOME images w/o the gray background but the issue is that for
most of the definitions I want the output bubble to show and for others I
want the comments. Snap doesn't export those so I needed to screenshot.

> - All images should be in img/somewhere
> 
> OK. I put them in img/prog/data/ and pushed them in.
> - The HTML pages should have an HTML 5 doctype. <!DOCTYPE html>
> - Snap, should be written as <span class="snap>snap</span> whenever
>   used in HTML.
> 
> OK. That probably needs to be fixed in other labs as well...
> 
> Finally, @xtitter https://github.com/xtitter Should be add the link to
> this lab in Berkeley_BJC? Or just link to it on the CS10 page?
> 
> I would add it.

Again, thanks for taking a close look!
Gerald

**Comment by cycomachead** [comment]
Awesome!

I didn't realize you wanted students to use the exact same coordinates provided, that makes sense. I thought they were just example data at the beginning. I might add a note saying that they'd be used for the first part of lab, or something along those lines.

In terms of the split block, I think students have a decent grasp now, but I don't think they've quite realized to how to import a file to a list. The map with split might throw some people off, but I think it's a good example, especially since it's the best way to handle a CSV in Snap.

I'll also try to do some reading about the encoding of images. I'd read that almost anything bigger than a small image is ~25% bigger when encoded as base64. 

But you're right that we still need the background when showing a reporter...no way around that for now.

**Comment by fractor** [comment]
Hi,

> I didn't realize you wanted students to use the exact same coordinates
> provided, that makes sense. I thought they were just example data at the
> beginning. I might add a note saying that they'd be used for the first
> part of lab, or something along those lines.

Done (in my part of the repository).

I'll also try to do some reading about the encoding of images. I'd read

> that almost anything bigger than a small image is ~25% bigger when encoded
> as base64.

So that's interesting: Yes it's 25% more data to download but that's
through an established connection. While any external image needs a new
connection which has high latency. I really don't know what the trade-off
is. I would think for small images like these a new connection is worse
than inline base64. But that's a guess.

Gerald

**Pull request merged**
