### PR TITLE
Merge LLAB with bjc-r

### LINKED ISSUE #332: moving LLAB out to its own repo
So, don't make any more changes in /admin in this repo... or, if you have to, make sure you either get or will eventually get the functionality over to the corresponding parts of the llab repo.

There will be changes to make here when we are ready to merge llab back in:
- [x] get rid of /admin, and make a submodule from the llab repo
- [x] fix content: reference the new loader file name/location
- [ ] did we fix the repo-root issue in llab?  If so, fix every absolute link to do the right thing

more...

@gissues:{"order":87.5,"status":"inprogress"}

### PR DESCRIPTION
**Pull request by cycomachead**
Fixes #332 
@xtitter @peterasujan Take a look!

I don't think this is quite ready, but everything seems to work, so it should be mostly done. 
Also take a look at llab since there's a lot going on with that branch
@gissues:{"order":75,"status":"inprogress"}

### CODE REVIEW

**Comment by cycomachead** [comment]
To do:
- [ ] The course listings page generates bad links which end in `&course=` and break... There's two bugs here: 1) query strings should also being with ? 2) I should prevent JS from running there...
- [ ] Topic pages don't have their title reset correct. This is likely a `.header` thing which I need to fix.
  (This is easy since I'm starting to refactor other parts of the code)

**Comment by xtitter** [comment]
Lets talk about this tomorrow, like with words.  I've been working in 
the llab repo, not in the bjc-r branch, which maybe is the right thing? 
  Wrote a verrrrry simple user class tonight, which sucks.

  <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
  Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
  Computer Science Education         U.C. Berkeley, 329 Soda Hall

**Comment by cycomachead** [comment]
Sure. I've also been working in llab. Making tons of progress on fixing stuff and the CSS as well. 

There's a `bjc-integration` branch of llab which I'm working out of for those changes. 

Submodules are...interesting. So far things seem to be working out.

**Comment by cycomachead** [comment]
So, I think this is pretty darn close to good! :) I posted in the llab repo, but someone take a look at this and let me know.

**Comment by cycomachead** [comment]
Play with things here:
http://cycomachead.github.io/bjc-r/

Still a WIP

**Comment by cycomachead** [comment]
@xtitter This is ready! :)

**Pull request merged**
