### PR TITLE
HTML5 Doctype, Larger iframes, and Documentation

### PR DESCRIPTION
**Pull request by cycomachead**
There's a lot of files that are changed, but most are small changes.

1) Vast majority of file changes are to move to HTML5 doctypes. 
2) I made a couple changes to the way iframes are handled so that they are now in a div. The upside is that their height now scales with the window height. (Course sharing videos still need work.)
3) README now has some WIP documentation, but it's a start!
I gave it a structure we can hopefully expand. It also includes basic license info, which we should probably clarify a bit more as well.
4) There's terrible diff cruft in bjc-loader due to whitespace changes for some reason... I can go back and fix it if necessary.
5) The links in the Berkeley_BJC course page are now more relative. I'm hoping to continually make more and more links relative instead of using /bjc-r

I think this is ready to merge, but I'd like someone else to give it a look over, just to be sure!

### CODE REVIEW

**Comment by cycomachead** [comment]
Any comments? I'd like to merge these changes then work on fixing the image width and height properties.

**Comment by peterasujan** [comment]
Looks good. I wasn't able to see the effects of 2), however. Can you give an example of a page that this should fix? I tried http://cycomachead.github.io/bjc-r/admin/empty-curriculum-page.html?src=http://www.bitsbook.com/wp-content/uploads/2008/12/chapter1.pdf&topic=berkeley_bjc/intro/broadcast-animations-music.topic&step=1&title=%20Blown%20To%20Bits:%20Chapter%201%20&course=berkeley_bjc.html but neither chrome nor firefox showed any change when I messed with the window size.

**Comment by cycomachead** [comment]
Try this:
http://cycomachead.github.io/bjc-r/admin/empty-curriculum-page.html?src=http://www.bitsbook.com/wp-content/uploads/2008/12/chapter2.pdf&topic=berkeley_bjc/intro/building-blocks.topic&step=3&title=%20Blown%20To%20Bits:%20Chapter%202%20&course=berkeley_bjc.html

How does that look?

**Comment by peterasujan** [comment]
I'm still not seeing any change when I make the window smaller.

**Comment by cycomachead** [comment]
Rejecting Pull Request to split into smaller chunks.

**Pull request closed without merging**
