### PR TITLE
Fixed issue involving topics-within-topics, made quiz styling prettier, added ability to hide stuff from topics.

### PR DESCRIPTION
**Pull request by peterasujan**

### CODE REVIEW

**Comment by cycomachead** [comment]
Nice work on the quiz changes! Simple and clean!

**Comment by xtitter** [comment]
What was the issue with topics-within-topics?   Ah, that the nav bar wasn't showing up, I'm guessing.

**Comment by xtitter** [comment]
I'll merge -- quiz styling looks great, etc.  Can you make one addition: when you see feedback, can the vertical line on the left border of that div be red if the answer is incorrect or green if it is correct?

**Comment by peterasujan** [comment]
Yep, topic-within-topic was just breaking stuff left and right (nav bar, multiple titles showing up).
I'll do the vertical line coloring a little later today.

**Pull request merged**
