### PR TITLE
Create cs10_su17.html

### PR DESCRIPTION
**Pull request by Laralinmcc**

### CODE REVIEW

**Comment by straversi** [comment]
Has this just changed the spring file? If so we need to keep the spring file around and just add a summer one. Then we add the link to the summer one here: https://github.com/beautyjoy/bjc-r/blob/gh-pages/index.html

**Comment by Laralinmcc** [comment]
Yea, I just changed the spring file because I was lazy and spring is linked
to our summer website :P

I can make a new file

**Comment by Laralinmcc** [comment]
Oh wait, but I changed the name. Nvm I will fix.

**Comment by straversi** [comment]
Committed separately all good

**Pull request closed without merging**
