### PR TITLE
Google Analytics

### LINKED ISSUE #249: Google analytics?
Can we use them?

I can fix this pretty easily...

### PR DESCRIPTION
**Pull request by cycomachead**
Fixes #249

This also starts to use a CDN in a couple places and makes some style fixes and updates the CS10 SP14 course.

### CODE REVIEW

**Comment by cycomachead** [comment]
https://github.com/beautyjoy/bjc-r/pull/269/files?w=0

View w/o whitespace differences..

**Comment by cycomachead** [comment]
@peterasujan @xtitter 

I'd like 'sign off' before merging...

**Comment by cycomachead** [comment]
https://github.com/beautyjoy/bjc-r/pull/269/files?w=0
Here is the diff w/o whitespace issues...

I'd rather merge this before too much work is done on my other request because there could be a bit of a merge mess...

**Comment by peterasujan** [comment]
Seems fine to me!

**Pull request merged**
