### PR TITLE
Concurrency lab update

### PR DESCRIPTION
**Pull request by straversi**
New subset problem
Consolidated pages
Minor updates to Serial vs. Parallel
New leaner multiple broadcasts

### CODE REVIEW

**Comment by straversi** [comment]
Dan would like to add a quiz

**Comment by straversi** [comment]
Lara: 👍

**Comment by straversi** [comment]
Staff meeting: merging, TA's to review before their respective labs this week (9/26/16). Expect small fixes

**Comment by cycomachead** [comment]
The fact that we just replaced the screenshots suggests that the bug / difference in Snap! was actually found. It seems like this lab now probably needs some more review...unless I'm misremembering something about the bug in that problem...

**Comment by straversi** [comment]
Whoa sorry Michael, missed this comment. We removed the bug for now and opted to turn the focus of the page toward a discussion of time-sharing instead. Let us know what you think!

**Pull request merged**
